### ISSUE TITLE
Device Type must be iPhone

### ISSUE THREAD

**Issue by rodalton** [ibm-watson-iot/iot-starter-for-ios#7]
Running this app via Xcode Simulator, look like the device type must be 'iPhone' or the app can't connect to our IoT Platform on IBM Cloud. I can see this is hard-coded as a constant. 

Should either mention in documentation or allow device type be defined in the UI?

**Comment by robert17** [comment]
From the README, under section `2. Connect to an IoT organization as a registered device`, there is a brief mention of this, `Next, you must register your device with your organization. When registering your device, create a new device type called iPhone (case sensitive).`

FYI, this application has not been updated/maintained in quite some time (over a year).
