### ISSUE TITLE
Reason code 5

### ISSUE THREAD

**Issue by afilkevich** [ibm-watson-iot/iot-starter-for-ios#8]
I create deviceType Iphone 
![photo2](https://user-images.githubusercontent.com/21995172/36717774-0ef991cc-1ba8-11e8-9446-2ff4313c493b.jpg)
![photo1](https://user-images.githubusercontent.com/21995172/36717775-0f2e0998-1ba8-11e8-9070-ae2a0511cf63.jpg)

,and add device . but when i connect  to iot - i have failed with code 5

**Comment by benbakowski** [comment]
Hi there,

Have you registered the device in IoT? Before a device can connect, it needs to be registered. Looking in the logs I can see:

```
 auth failed (Device/gateway not found in database): ClientID='d:t2oecx:iPhone:iphone1',
```

Note the capitalization - you appear to be trying to connect with a deviceType of "iPhone" and deviceId "iphone1", so you'll need to ensure a device matching these is registered.

**Comment by afilkevich** [comment]
Hi!
yes, i registered device before connect. but have this problem.

**Comment by benbakowski** [comment]
Do you have a connection policy defined which your device doesn't satisfy?

**Comment by afilkevich** [comment]
Maybe yes. Because when i set default rule=TLS optional in connect security.It's ok. Thanks
